using FluentValidation;
using Microsoft.AspNetCore.Diagnostics;

namespace Aurora.Coinly.Api.Middlewares;

public sealed class ValidationExceptionHandler(
    IProblemDetailsService problemDetailsService) : IExceptionHandler
{
    public async ValueTask<bool> TryHandleAsync(
        HttpContext httpContext,
        Exception exception,
        CancellationToken cancellationToken)
    {
        if (exception is not ValidationException validationException)
        {
            return false;
        }

        httpContext.Response.StatusCode = StatusCodes.Status400BadRequest;

        var context = new ProblemDetailsContext
        {
            HttpContext = httpContext,
            Exception = exception,
            ProblemDetails = new ProblemDetails
            {
                Type = "https://tools.ietf.org/html/rfc7231#section-6.5.1",
                Title = "Internal Server Error",
                Status = StatusCodes.Status400BadRequest,
                Detail = "One or more validation error ocurred. See the errors property for details."
            }
        };

        var error = validationException.Errors
            .GroupBy(x => x.PropertyName)
            .ToDictionary(
                x => x.Key,
                x => x.Select(y => y.ErrorMessage).ToArray());

        context.ProblemDetails.Extensions.Add("errors", error);

        return await problemDetailsService.TryWriteAsync(context);
    }
}